# Liste der Hersteller von DCC-Dekodern
class MANUFACTURER:
    
    LIST_OF_MANUFACTURERS = [
        (1, "CML Electronics Limited"),
        (2, "Train Technology"),
        (11, "NCE Corporation"),
        (12, "Wangrow Electronics"),
        (13, "Public Domain & Do-It-Yourself Decoders"),
        (14, "PSI –Dynatrol"),
        (15, "Ramfixx Technologies (Wangrow)"),
        (17, "Advance IC Engineering"),
        (18, "JMRI"),
        (19, "AMW"),
        (20, "T4T – Technology for Trains GmbH"),
        (21, "Kreischer Datentechnik"),
        (22, "KAM Industries"),
        (23, "S Helper Service"),
        (24, "MoBaTron.de"),
        (25, "Team Digital, LLC"),
        (26, "MBTronik – PiN GITmBH"),
        (27, "MTH Electric Trains, Inc."),
        (28, "Heljan A/S"),
        (29, "Mistral Train Models"),
        (30, "Digsight"),
        (31, "Brelec"),
        (32, "Regal Way Co. Ltd"),
        (33, "Praecipuus"),
        (34, "Aristo-Craft Trains"),
        (35, "Electronik & Model Produktion"),
        (36, "DCCconcepts"),
        (37, "NAC Services, Inc"),
        (38, "Broadway Limited Imports, LLC"),
        (39, "Educational Computer, Inc."),
        (40, "KATO Precision Models"),
        (41, "Passmann"),
        (42, "Digirails"),
        (43, "Ngineering"),
        (44, "SPROG-DCC"),
        (45, "ANE Model Co, Ltd"),
        (46, "GFB Designs"),
        (47, "Capecom"),
        (48, "Hornby Hobbies Ltd"),
        (49, "Joka Electronic"),
        (50, "N&Q Electronics"),
        (51, "DCC Supplies, Ltd"),
        (52, "Krois-Modell"),
        (53, "Rautenhaus Digital Vertrieb"),
        (54, "TCH Technology"),
        (55, "QElectronics GmbH"),
        (56, "LDH"),
        (57, "Rampino Elektronik"),
        (58, "KRES GmbH"),
        (59, "Tam Valley Depot"),
        (60, "Bluecher-Electronic"),
        (61, "TrainModules"),
        (62, "Tams Elektronik GmbH"),
        (63, "Noarail"),
        (64, "Digital Bahn"),
        (65, "Gaugemaster"),
        (66, "Railnet Solutions, LLC"),
        (67, "Heller Modenlbahn"),
        (68, "MAWE Elektronik"),
        (69, "E-Modell"),
        (70, "Rocrail"),
        (71, "New York Byano Limited"),
        (72, "MTB Model"),
        (73, "The Electric Railroad Company"),
        (74, "PpP Digital"),
        (75, "Digitools Elektronika, Kft"),
        (76, "Auvidel"),
        (77, "LS Models Sprl"),
        (78, "Tehnologistic (train-O-matic)"),
        (79, "Hattons Model Railways"),
        (80, "Spectrum Engineering"),
        (81, "GooVerModels"),
        (82, "HAG Modelleisenbahn AG"),
        (83, "JSS-Elektronic"),
        (84, "Railflyer Model Prototypes, Inc."),
        (85, "Uhlenbrock GmbH"),
        (86, "Wekomm Engineering, GmbH"),
        (87, "RR-Cirkits"),
        (88, "HONS Model"),
        (89, "Pojezdy.EU"),
        (90, "Shourt Line"),
        (91, "Railstars Limited"),
        (92, "Tawcrafts"),
        (93, "Kevtronics cc"),
        (94, "Electroniscript, Inc."),
        (95, "Sanda Kan Industrial, Ltd."),
        (96, "PRICOM Design"),
        (97, "Doehler & Haas"),
        (98, "Harman DCC"),
        (99, "Lenz Elektronik GmbH"),
        (100, "Trenes Digitales"),
        (101, "Bachmann Trains"),
        (102, "Integrated Signal Systems"),
        (103, "Nagasue System Design Office"),
        (104, "TrainTech"),
        (105, "Computer Dialysis France"),
        (106, "Opherline1"),
        (107, "Phoenix Sound Systems, Inc."),
        (108, "Nagoden"),
        (109, "Viessmann Modellspielwaren GmbH"),
        (110, "AXJ Electronics"),
        (111, "Haber & Koenig Electronics GmbH (HKE)"),
        (112, "LSdigital"),
        (113, "QS Industries (QSI)"),
        (114, "Benezan Electronics"),
        (115, "Dietz Modellbahntechnik"),
        (116, "MyLocoSound"),
        (117, "cT Elektronik"),
        (118, "MÜT GmbH"),
        (119, "W. S. Ataras Engineering"),
        (120, "csikos-muhely"),
        (122, "Berros"),
        (123, "Massoth Elektronik, GmbH"),
        (124, "DCC-Gaspar-Electronic"),
        (125, "ProfiLok Modellbahntechnik GmbH"),
        (126, "Möllehem Gårdsproduktion"),
        (127, "Atlas Model Railroad Products"),
        (128, "Frateschi Model Trains"),
        (129, "Digitrax"),
        (130, "cmOS Engineering"),
        (131, "Trix Modelleisenbahn"),
        (132, "ZTC"),
        (133, "Intelligent Command Control"),
        (134, "LaisDCC"),
        (135, "CVP Products"),
        (136, "NYRS"),
        (138, "Train ID Systems"),
        (139, "RealRail Effects"),
        (140, "Desktop Station"),
        (141, "Throttle-Up (Soundtraxx)"),
        (142, "SLOMO Railroad Models"),
        (143, "Model Rectifier Corp."),
        (144, "DCC Train Automation"),
        (145, "Zimo Elektronik"),
        (146, "Rails Europ Express"),
        (147, "Umelec Ing. Buero"),
        (148, "BLOCKsignalling"),
        (149, "Rock Junction Controls"),
        (150, "Wm. K. Walthers, Inc."),
        (151, "Electronic Solutions Ulm GmbH"),
        (152, "Digi-CZ"),
        (153, "Train Control Systems"),
        (154, "Dapol Limited"),
        (155, "Gebr. Fleischmann GmbH & Co."),
        (156, "Nucky"),
        (157, "Kuehn Ing."),
        (158, "Fucik"),
        (159, "LGB (Ernst Paul Lehmann Patentwerk)"),
        (160, "MD Electronics"),
        (161, "Modelleisenbahn GmbH (formerly Roco)"),
        (162, "PIKO"),
        (163, "WP Railshops"),
        (164, "drM"),
        (165, "Model Electronic Railway Group"),
        (166, "Maison de DCC"),
        (167, "Helvest Systems GmbH"),
        (170, "AuroTrains"),
        (173, "Arnold – Rivarossi"),
        (186, "BRAWA Modellspielwaren GmbH & Co."),
        (204, "Con-Com GmbH"),
        (225, "Blue Digital"),
        (238, "NMRA Reserved (for extended ID #’s)")
    ]
    
    @classmethod
    def list_manufacturer_names(cls):
        print(f"{'ID':>4}\tHersteller Name")
        for i in cls.LIST_OF_MANUFACTURERS:
            print(f"{i[0]:>4}\t{i[1]}")
    
    @classmethod
    def get_manufacturer_name(cls, manufacturer_id):
        if manufacturer_id > 0 and manufacturer_id < 256:
            for i in cls.LIST_OF_MANUFACTURERS:
                if i[0] == manufacturer_id:
                   return i[1]
        return "n/a"


if __name__ == "__main__":
    mans = MANUFACTURER
    mans.list_manufacturer_names()
    print(0, mans.get_manufacturer_name(0))
    print(3, mans.get_manufacturer_name(3))
    print(152, mans.get_manufacturer_name(145))
    print(85, mans.get_manufacturer_name(85))
    print(999, mans.get_manufacturer_name(999))
    